backend:
  name: git-gateway
  branch: main

locale: 'pt'

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "content/noticias"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Escritório" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Imagem Destaque", name: "featured_image", widget: "image", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }